[book]
authors = ["Bobby Chen"]
language = "en"
multilingual = false
src = "src"
title = "ChenBobby.com"

[output.html]
curly-quotes = true
additional-css = ["static/css/custom.css"]
cname = "chenbobby.com"